### ISSUE TITLE
bStats doesn't appear to work this is what I get in console:

### ISSUE THREAD

**Issue by Kame03** [Bastian/bstats-metrics#116]
`[09:19:15] [bStats-Metrics/INFO]: [KPManager] Sent bStats metrics data: {"playerAmount":1,"onlineMode":1,"bukkitVersion":"REMOVED-IT (MC: 1.19.3)","bukkitName":"CraftBukkit","javaVersion":"17.0.2","osName":"Linux","osArch":"aarch64","osVersion":"5.15.0-1027-oracle","coreCount":4,"service":{"pluginVersion":"v1.8","id":17490,"customCharts":[]},"serverUUID":"REMOVED-IT","metricsVersion":"3.0.0"}
[09:19:15] [bStats-Metrics/WARN]: [KPManager] Could not submit bStats metrics data
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/api/v2/data/bukkit
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
	at in.rs.milivojevic.KPManager.utils.Metrics$MetricsBase.sendData(Metrics.java:329) ~[?:?]
	at in.rs.milivojevic.KPManager.utils.Metrics$MetricsBase.lambda$submitData$4(Metrics.java:298) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	[09:25:36] [Spigot Metrics Thread/INFO]: [Metrics] Received fatal alert: internal_error
	`

**Comment by Bastian** [comment]
Hey, 429 just means that your plugin got ratelimited for sending data too often. This is very common (especially after a server start) and not a bug. See https://github.com/Bastian/bstats-metrics/issues/86
