### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by Bastian** [Bastian/bStats-Metrics#62]
```
22:10:11 [INFO]: Allow unsafe renegotiation: false
22:10:11 [INFO]: Allow legacy hello messages: true
22:10:11 [INFO]: Is initial handshake: true
22:10:11 [INFO]: Is secure renegotiation: false
22:10:11 [INFO]: Thread-34, setSoTimeout(0) called
22:10:11 [INFO]: Thread-34, the previous server name in SNI (type=host_name (0), value=bStats.org) was replaced with (type=host_name (0), value=bStats.org)
22:10:11 [INFO]: Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 for TLSv1.1
22:10:11 [INFO]: Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 for TLSv1.1
22:10:11 [INFO]: Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 for TLSv1.1
22:10:11 [INFO]: %% No cached client session
22:10:11 [INFO]: update handshake state: client_hello[1]
22:10:11 [INFO]: upcoming handshake states: server_hello[2]
22:10:11 [INFO]: *** ClientHello, TLSv1.2
22:10:11 [INFO]: RandomCookie:  GMT: 1581958675 bytes = { 29, 173, 209, 85, 78, 39, 30, 178, 57, 81, 183, 157, 198, 154, 57, 236, 177, 149, 56, 210, 137, 13, 12, 74, 220, 126, 49, 194 }
22:10:11 [INFO]: Session ID:  {}
22:10:11 [INFO]: Cipher Suites: [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384, TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDH_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDH_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA, SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
22:10:11 [INFO]: Compression Methods:  { 0 }
22:10:11 [INFO]: Extension elliptic_curves, curve names: {secp256r1, secp384r1, secp521r1}
22:10:11 [INFO]: Extension ec_point_formats, formats: [uncompressed]
22:10:11 [INFO]: Extension signature_algorithms, signature_algorithms: SHA512withECDSA, SHA512withRSA, SHA384withECDSA, SHA384withRSA, SHA256withECDSA, SHA256withRSA, SHA256withDSA, SHA224withECDSA, SHA224withRSA, SHA224withDSA, SHA1withECDSA, SHA1withRSA, SHA1withDSA, MD5withRSA
22:10:11 [INFO]: Extension extended_master_secret
22:10:11 [INFO]: ***
22:10:11 [INFO]: Thread-34, WRITE: TLSv1.2 Handshake, length = 201
22:10:11 [INFO]: Thread-34, WRITE: SSLv2 client hello message, length = 206
22:10:11 [INFO]: Thread-34, READ: TLSv1 Alert, length = 2
22:10:11 [INFO]: Thread-34, RECV TLSv1.2 ALERT:  fatal, handshake_failure
22:10:11 [INFO]: Thread-34, called closeSocket()
22:10:11 [INFO]: Thread-34, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
22:10:11 [INFO]: Thread-34, called close()
22:10:11 [INFO]: Thread-34, called closeInternal(true)
22:10:11 [WARN]: Could not submit plugin stats of WorldEdit
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_242]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1127) ~[?:1.8.0_242]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367) ~[?:1.8.0_242]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395) ~[?:1.8.0_242]
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379) ~[?:1.8.0_242]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_242]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_242]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340) ~[?:1.8.0_242]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315) ~[?:1.8.0_242]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264) ~[?:1.8.0_242]
        at com.sk89q.worldedit.bukkit.bstats.bukkit.Metrics.sendData(Metrics.java:351) ~[?:?]
        at com.sk89q.worldedit.bukkit.bstats.bukkit.Metrics.access$300(Metrics.java:30) ~[?:?]
        at com.sk89q.worldedit.bukkit.bstats.bukkit.Metrics$2.run(Metrics.java:307) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**Comment by Bastian** [comment]
Probably fixed in the new Metrics classes
